var data = {
	images: [
		{
			src: ["https://i.imgur.com/XaeP0ZF.jpg"],
			thumbnail: "https://i.imgur.com/eiaQ5bK.jpg",
			title: "Lucina Spilled Some Yogurt",
			artist: "Anonymous Artist",
			artist_url: null,
			art_url: null,
			desc: "Artist did not wish to be named or identified. An inside joke between the artist and myself. It's yogurt. Why is it marked NSFW? It's just yogurt.",
			date_str: "May 2017",
			tags: [""],
			hidden: true
		},
		{
			src: ["https://i.imgur.com/RPVOpBi.png"],
			thumbnail: "https://i.imgur.com/H2WRcUR.jpg",
			title: "Hooters Lucina (Anonymous Artist)",
			artist: "Anonymous Artist",
			artist_url: null,
			art_url: null,
			desc: "Artist did not wish to be named or identified. The first Hooters Lucina! Includes NSFW variants [not included here].",
			date_str: "July 2018",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/etMkAct.png"],
			thumbnail: "https://i.imgur.com/WL9zGCq.jpg",
			title: "Christmas Hooters Lucina (Anonymous Artist)",
			artist: "Anonymous Artist",
			artist_url: null,
			art_url: null,
			desc: "Artist did not wish to be named or identified. Not a commission, but was a gift for Christmas",
			date_str: "December 2018",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/ScrrpAv.jpg"],
			thumbnail: "https://i.imgur.com/ktkABoP.jpg",
			title: "Hooters Lucina (VialNite)",
			artist: "VialNite",
			artist_url: "https://twitter.com/VialNite",
			art_url: "https://twitter.com/VialNite/status/1394675039161753609",
			desc: "The first publicly published Hooters Lucina. I love the legwear as well as the cute Feh and the orbs on a post in the logo.",
			date_str: "May 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/nptagAl.jpg"],
			thumbnail: "https://i.imgur.com/w4HPbrr.jpg",
			title: "Hooters Lucina (Vallurite)",
			artist: "Vallurite",
			artist_url: "https://twitter.com/Vallurite",
			art_url: "https://twitter.com/Vallurite/status/1394692198151688192",
			desc: "I love how this one turned out. Her smile is so nice, and I really like Vallurite's style.",
			date_str: "May 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/c6WlxG6.png", "https://i.imgur.com/vMKoJ4z.png"],
			thumbnail: "https://i.imgur.com/TOzgr8P.jpg",
			title: "Hooters Lucina (SonicHeroXD)",
			artist: "SonicHeroXD",
			artist_url: "https://twitter.com/SonicHeroXD",
			art_url: "https://twitter.com/SonicHeroXD/status/1399120844639584261",
			desc: "It was wonderfully done by SonicHeroXD! <3 There is also a spicy lingerie variant in the Twitter source!",
			date_str: "May 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/AkMNIvr.jpg"],
			thumbnail: "https://i.imgur.com/l90cVfD.jpg",
			title: "Hooters Lucina (m1n0f2e1_)",
			artist: "m1n0f2e1_",
			artist_url: "https://twitter.com/m1n0f2e1_",
			art_url: "https://skeb.jp/@m1n0f2e1_/works/6",
			desc: "This was my first Skeb commission. It turned out very cute! I really love the brightness of the colors.",
			date_str: "June 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/UCipSh3.jpg", "https://i.imgur.com/wLaZUYk.png"],
			thumbnail: "https://i.imgur.com/QWmbES4.jpg",
			title: "Hooters Lucina (PPPMMMRRROOO)",
			artist: "PPPMMMRRROOO",
			artist_url: "https://twitter.com/PPPMMMRRROOO",
			art_url: "https://skeb.jp/@PPPMMMRRROOO/works/1",
			desc: "This one has two versions: one with warmer lighting and one with cooler lighting. I like the sitting pose, which was something new and different at the time.",
			date_str: "June 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/1swR4Cg.jpg"],
			thumbnail: "https://i.imgur.com/rUjzNRE.jpg",
			title: "Hooters Lucina (nekko_donburi)",
			artist: "nekko_donburi",
			artist_url: "https://twitter.com/nekko_donburi",
			art_url: "https://skeb.jp/@nekko_donburi/works/1",
			desc: "Another one with her sitting down but with a view from behind instead. It's really creative how the background resembles beer.",
			date_str: "June 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/mv7v0xR.jpg"],
			thumbnail: "https://i.imgur.com/HwNTLdH.jpg",
			title: "Lucina HYPE!!!! (Vallurite)",
			artist: "Vallurite",
			artist_url: "https://twitter.com/Vallurite",
			art_url: "https://twitter.com/Vallurite/status/1403458247458275345",
			desc: "I love the lines that emphasize this moment of hype. LET'S GOOO!",
			date_str: "June 2021",
			tags: [""],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/lVHF8Bh.jpg"],
			thumbnail: "https://i.imgur.com/ualTckk.jpg",
			title: "Hooters Lucina (Densho_Hiyoko)",
			artist: "Densho_Hiyoko",
			artist_url: "https://twitter.com/Densho_Hiyoko",
			art_url: "https://twitter.com/Densho_Hiyoko/status/1403724784450506752",
			desc: "I commissioned Densho_Hiyoko, who draws cute chibi Lucina doodles on Twitter, to draw a Hooters Lucina. She turned out so cute and pretty!",
			date_str: "June 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/ccyatcl.jpg"],
			thumbnail: "https://i.imgur.com/Mt00W76.jpg",
			title: "Hooters Lucina (wawatiku)",
			artist: "wawatiku",
			artist_url: "https://twitter.com/wawatiku",
			art_url: "https://twitter.com/wawatiku/status/1407901143443800064",
			desc: "This time it was done by wawatiku. It's lovely! I especially love the hair and the background - it's all so pretty.",
			date_str: "June 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/CM2hePj.jpg"],
			thumbnail: "https://i.imgur.com/x0nj0fL.jpg",
			title: "Hooters Lucina (AKN_646)",
			artist: "AKN_646",
			artist_url: "https://twitter.com/AKN_646",
			art_url: "https://twitter.com/akn_646/status/1408456950728118275",
			desc: "This time is by AKN. Very cute and very pretty - I love it!",
			date_str: "June 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/kTenxhH.jpg"],
			thumbnail: "https://i.imgur.com/qyukxm0.jpg",
			title: "Hooters Lucina (Ihsnet)",
			artist: "Ihsnet",
			artist_url: "https://twitter.com/Ihsnet",
			art_url: "https://twitter.com/Ihsnet/status/1409003004351635457",
			desc: "This time it's done by Ihsnet! I especially like the long legs and how the boots resemble those from her regular outfit.",
			date_str: "June 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/iQA108g.png"],
			thumbnail: "https://i.imgur.com/JDwWXz8.jpg",
			title: "Hooters Lucina (SMGold)",
			artist: "SMGold",
			artist_url: "https://twitter.com/SMGold_",
			art_url: null,
			desc: "It's wonderful! I love the pose and expression: demure but still warm.",
			date_str: "June 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/jCdkav2.png"],
			thumbnail: "https://i.imgur.com/Fwvi94d.jpg",
			title: "Hooters Lucina (B_PearlWhite)",
			artist: "B_PearlWhite",
			artist_url: "https://twitter.com/B_PearlWhite",
			art_url: "https://twitter.com/B_PearlWhite/status/1410617732656107529",
			desc: "This is the only one with full-leg leggings other than the original Hooters Lucina from a few years ago (there are a few with stockings and boots however). I also like the bubbly background. It's very nice!",
			date_str: "July 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/8WO5lvZ.png"],
			thumbnail: "https://i.imgur.com/PIbWnGJ.jpg",
			title: "Hooters Lucina (frogbians)",
			artist: "frogbians",
			artist_url: "https://twitter.com/frogbiansVEVO",
			art_url: "https://twitter.com/frogbiansVEVO/status/1417535041949691904",
			desc: "I really like the design of the cute footwear and legwear as well as the food!",
			date_str: "July 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/cVwQh9z.jpg"],
			thumbnail: "https://i.imgur.com/cUaFeGL.jpg",
			title: "Hooters Lucina (zaki_btw)",
			artist: "zaki_btw",
			artist_url: "https://twitter.com/zaki_btw",
			art_url: null,
			desc: "The atmosphere of this piece is great, and the lighting and shading help capture it really well.",
			date_str: "July 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/IdkEhPb.png"],
			thumbnail: "https://i.imgur.com/UVAQhqV.jpg",
			title: "Hooters Lucina (harunn2288)",
			artist: "harunn2288",
			artist_url: "https://twitter.com/harunn2288",
			art_url: "https://skeb.jp/@harunn2288/works/76",
			desc: "This is harunn's take on Hooters Lucina, and it turned out really pretty! Her smile is cute, and the lines in the background make this piece seem dynamic and lively!",
			date_str: "July 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/on6FNHP.jpg", "https://i.imgur.com/MqbFNgs.jpg"],
			thumbnail: "https://i.imgur.com/jH9IJ5E.jpg",
			title: "Hooter Lucina (kalruna)",
			artist: "kalruna",
			artist_url: "https://twitter.com/kalruna_art",
			art_url: "https://twitter.com/kalruna_art/status/1430968289182760962",
			desc: "This is kalruna's Hooters Lucina! This has a shirt-on version and a topless version. I really love the warm colors, lighting, and tone. She's enjoying a mug of beer by the bar after a long day of work. It's so very nice and cozy!",
			date_str: "July 2021",
			tags: ["hooters", "nsfw"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/PRhT6Tt.png"],
			thumbnail: "https://i.imgur.com/fZqwoFj.jpg",
			title: "Hooters Lucina (BBK13zK)",
			artist: "BBK13zK",
			artist_url: "https://twitter.com/bbk13z",
			art_url: "https://twitter.com/bbk13z/status/1422017312316481538",
			desc: "BBK's Hooters Lucina! Again, Lucina's smile is so nice. A happy Lucina is a great Lucina! The heels are a nice touch too. Very pretty!",
			date_str: "July 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/vMXEesI.jpg"],
			thumbnail: "https://i.imgur.com/rcMOXEj.jpg",
			title: "Hooters Lucina (Patdarux Dream)",
			artist: "Patdarux Dream",
			artist_url: "https://twitter.com/patdarux",
			art_url: "https://twitter.com/patdarux/status/1419066117432217600",
			desc: "This is Patdarux's Hooters Lucina! I like the cute Feh in the logo on the shirt, and I really like the seaside paradise background!",
			date_str: "July 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/lMFDdBV.png"],
			thumbnail: "https://i.imgur.com/YJ2KXWR.jpg",
			title: "Hooters Lucina (azure_monarch)",
			artist: "azure_monarch",
			artist_url: "https://twitter.com/azure_monarch",
			art_url: "https://twitter.com/azure_monarch/status/1419380538205380608",
			desc: "The Lucina art community's very own azure_monarch has done a Hooters Lucina! I've watched his growth as an artist for a long while now, and I look forward to his future work. I really like Lucina's smile and the beer, and the lighting is impressive! Keep it up!<br/>azure_monarch also came up with Hooters Lucina independently from me back in 2018 in this <a href='https://twitter.com/azure_monarch/status/981019322209337344'>Tweet</a>.",
			date_str: "July 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/tHCuhq4.jpg"],
			thumbnail: "https://i.imgur.com/6uW38Cp.jpg",
			title: "Lifeguard Lucina (GrimmelsDaThird)",
			artist: "GrimmelsDaThird",
			artist_url: "https://twitter.com/GrimmelsDaThird",
			art_url: "https://twitter.com/GrimmelsDaThird/status/1419697741681156098",
			desc: "A nice summertime piece of Lucina in a red lifeguard one-piece swimsuit. We've gotten a lot of different types of swimsuit art for Lucina, but I haven't seen a lifeguard one. A nice refreshing piece for a hot summer's day!",
			date_str: "July 2021",
			tags: [""],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/sTeqn0d.jpg"],
			thumbnail: "https://i.imgur.com/gBLQlwG.jpg",
			title: "Hooters Lucina & Tomboy Outback Lucina (cluseller)",
			artist: "cluseller",
			artist_url: "https://twitter.com/cluseller",
			art_url: "https://skeb.jp/@cluseller/works/60",
			desc: "Hooters Lucina with a Tomboy Outback Lucina by cluseller! This was an idea pitched to me by a friend, and I knew cluseller was the right artist for the job. I love their smiles and the deep blue of the hair (long and short). It turned out so wonderfully, and they're both so pretty. Which invitation would you accept?",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/E38bzcp.png"],
			thumbnail: "https://i.imgur.com/KbMnsNm.jpg",
			title: "Hooters Lucina (joysjsj00)",
			artist: "joysjsj00",
			artist_url: "https://www.instagram.com/joysjsj00/",
			art_url: null,
			desc: "This is a Hooters Lucina by Joy. This turned out really pretty and really cute! The artist was also great and very friendly. Lucina looks a little shy, but the pose shows confidence. And I really like how that's depicted.",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/nngQwJF.png"],
			thumbnail: "https://i.imgur.com/ZbLlw54.jpg",
			title: "Hooters Lucina (deeKei)",
			artist: "deeKei",
			artist_url: "https://twitter.com/_deeKei",
			art_url: "https://twitter.com/_deeKei/status/1425890035966959620",
			desc: "This is deeKei's take on Hooters Lucina! It's super pretty! The visor and the ponytail add the sportiness of a sports bar like Hooters. The friendly smile and wink are also very cute!",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/HqPH9Wr.jpg"],
			thumbnail: "https://i.imgur.com/Nic6DtB.jpg",
			title: "Lucina Paizuri (Devilukez10)",
			artist: "Devilukez10",
			artist_url: "https://twitter.com/Devilukez10",
			art_url: "https://twitter.com/Devilukez10/status/1427917077252165632",
			desc: "Lucina tried her best at a titfuck using her small breasts. She looks satisfied with the result! Part 1 of 2 commissions.",
			date_str: "August 2021",
			tags: ["nsfw"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/OSYbVI2.png"],
			thumbnail: "https://i.imgur.com/OsoD6Kc.jpg",
			title: "Hooters Lucina (NaijMizuho)",
			artist: "NaijMizuho",
			artist_url: "https://twitter.com/SnippyAsianGuy",
			art_url: "https://twitter.com/SnippyAsianGuy/status/1428413308411994113",
			desc: "This is NaijMizuho's very pretty Hooters Lucina! I'm a big fan of his Lucina artwork. I love Lucina's confident pose and, of course, her smile! It's just so pretty!<br/>This was a commission request in response to this <a href='https://twitter.com/SnippyAsianGuy/status/1423506971706208257'>Tweet</a>.",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/76KwElN.jpg"],
			thumbnail: "https://i.imgur.com/1krLRAI.jpg",
			title: "Hooters Lucina (tsunsune)",
			artist: "tsunsune",
			artist_url: "https://twitter.com/tsunsune",
			art_url: "https://twitter.com/tsunsune/status/1429400204013314052",
			desc: "This is tsunsune's Hooters Lucina! The artwork turned out so pretty: the lighting, colors, and atmosphere are so nice and bright and inviting. It's as if Lucina herself is waiting on you with a cute smile on her face! :D",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/0KRih0U.jpg"],
			thumbnail: "https://i.imgur.com/ALgsgOo.jpg",
			title: "Hooters Lucina (RayDango)",
			artist: "RayDango",
			artist_url: "https://twitter.com/ray_dango",
			art_url: "https://twitter.com/ray_dango/status/1429883492670840834",
			desc: "Hooters Lucina by RayDango! She looks super cute here, and RayDango's style adds to the cuteness really well. Service with a smile... and a bonus wink!",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/Ir796bU.png"],
			thumbnail: "https://i.imgur.com/xeRckC3.jpg",
			title: "Hooters Lucina (graysheartart)",
			artist: "graysheartart",
			artist_url: "https://twitter.com/graysheartart",
			art_url: null,
			desc: "I really like the outfit design for this: the tied-up shirt, the cute visor, and the orange socks. It turned out really cute, and it has a really refreshing quality about it!",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: true
		},
		{
			src: ["https://i.imgur.com/HwvGRJk.png"],
			thumbnail: "https://i.imgur.com/Amhda50.jpg",
			title: "Hooters Lucina (ArcEdo)",
			artist: "ArcEdo",
			artist_url: "https://twitter.com/Arc_Edo11",
			art_url: "https://twitter.com/Arc_Edo11/status/1435686491846553603",
			desc: "ArcEdo's Hooters Lucina is so pretty, and I love how it turned out! Feh the owl on the logo is always a hoot. The colors are all very lovely. Lucina's smile is also so precious. :) Nicely done!",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/ZXMy5az.png"],
			thumbnail: "https://i.imgur.com/oRpXHei.jpg",
			title: "Hooters Lucina (John Caden)",
			artist: "John Caden",
			artist_url: "https://twitter.com/JohnCaden64",
			art_url: "https://twitter.com/JohnCaden64/status/1431299136830197765",
			desc: "This is a Hooters Lucina by John Caden! It's so cute and so pretty! I love John's style, and I've been a fan of his Lucina artwork for a while. This was done amazingly well, and I especially like the expression he chose to draw! Please consider checking out his art on Twitter!",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/Qzzp5Xa.jpg"],
			thumbnail: "https://i.imgur.com/hFeuim5.jpg",
			title: "Hooters Lucina (eva02marina0)",
			artist: "eva02marina0",
			artist_url: "https://twitter.com/eva02marina0",
			art_url: "https://twitter.com/eva02marina0/status/1432698692608405511",
			desc: "This is Mari's Hooters Lucina artwork! I'm stunned by how beautiful this is. Lucina looks so pretty and so cute here! I love the bright and warm colors and, of course, Lucina's smile. It's all so lovely!",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: true
		},
		{
			src: ["https://i.imgur.com/kbpAZ1W.png"],
			thumbnail: "https://i.imgur.com/PB9ZMhm.jpg",
			title: "Hooters Lucina (OrenjiNoodle)",
			artist: "OrenjiNoodle",
			artist_url: "https://twitter.com/OrenjiNoodle",
			art_url: "https://twitter.com/OrenjiNoodle/status/1436008766353199105",
			desc: "OrenjiNoodle's Hooters Lucina is so cute! I really love how it turned out. The brightness of the colors and the contrast of the blue and orange are so visually nice. Adorable! Amazing work!",
			date_str: "September 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/7ADHqIx.jpg"],
			thumbnail: "https://i.imgur.com/hXiylRj.jpg",
			title: "Hooters Lucina (Seityr)",
			artist: "Seityr",
			artist_url: "https://twitter.com/Seityr_Art",
			art_url: "https://twitter.com/Seityr_Art/status/1436914514016886792",
			desc: "This is Seityr's Hooters Lucina! The colors give this a really nice refreshing feeling, and I love Lucina's smile and confident pose. It's all very pretty and very well done!",
			date_str: "September 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/G9QwHN2.jpg", "https://i.imgur.com/z6Ahcqy.jpg", "https://i.imgur.com/IxzHnO6.jpg", "https://i.imgur.com/D503m1I.jpg", "https://i.imgur.com/03JLEMK.jpg", "https://i.imgur.com/fd99dy8.jpg", "https://i.imgur.com/4YP001d.jpg", "https://i.imgur.com/UuJFJVF.jpg", "https://i.imgur.com/zb1LgAa.jpg", "https://i.imgur.com/qFN1Z8W.jpg", "https://i.imgur.com/hMhmw44.jpg", "https://i.imgur.com/EH0ptxt.jpg", "https://i.imgur.com/BVDbGiJ.jpg"],
			thumbnail: "https://i.imgur.com/V5qYbiz.jpg",
			title: "Sex with Summer Lucina (mazenda3378)",
			artist: "mazenda3378",
			artist_url: "https://twitter.com/mazenda3378",
			art_url: "https://skeb.jp/@mazenda3378/works/12",
			desc: "Sex with Lucina in her Cipher swimsuit at the beach! This one came with 9 preset variants by the artist. The provided .psd file also had some other options, so I was able to create some custom variants as well.",
			date_str: "September 2021",
			tags: ["nsfw"],
			hidden: false
		},
		{
			src: [""],
			thumbnail: "",
			title: "",
			artist: "",
			artist_url: "",
			art_url: "",
			desc: "",
			date_str: "",
			tags: [""],
			hidden: true
		}
	]
};