var data = {
	images: [
		{
			src: ["https://i.imgur.com/XaeP0ZF.jpg"],
			thumbnail: "https://i.imgur.com/eiaQ5bK.jpg",
			title: "Lucina Spilled Some Yogurt",
			artist: "Anonymous Artist",
			artist_url: null,
			art_url: null,
			desc: "Artist did not wish to be named or identified. An inside joke between the artist and myself. It's just yogurt.",
			date_str: "May 2017",
			tags: [""],
			hidden: true
		},
		{
			src: ["https://i.imgur.com/RPVOpBi.png"],
			thumbnail: "https://i.imgur.com/H2WRcUR.jpg",
			title: "Hooters Lucina (Anonymous Artist)",
			artist: "Anonymous Artist",
			artist_url: null,
			art_url: null,
			desc: "Artist did not wish to be named or identified. The first Hooters Lucina! Includes NSFW variants [not included here].",
			date_str: "July 2018",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/etMkAct.png"],
			thumbnail: "https://i.imgur.com/WL9zGCq.jpg",
			title: "Christmas Hooters Lucina (Anonymous Artist)",
			artist: "Anonymous Artist",
			artist_url: null,
			art_url: null,
			desc: "Artist did not wish to be named or identified. Not a commission, but was a gift for Christmas. The same anonymous artist who drew <span class='series-link' index='1'>this one</span>.",
			date_str: "December 2018",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/ScrrpAv.jpg"],
			thumbnail: "https://i.imgur.com/ktkABoP.jpg",
			title: "Hooters Lucina (VialNite)",
			artist: "VialNite",
			artist_url: "https://twitter.com/VialNite",
			art_url: "https://twitter.com/VialNite/status/1394675039161753609",
			desc: "The first publicly published Hooters Lucina. I love the legwear as well as the cute Feh and the orbs on a post in the logo.",
			date_str: "May 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/nptagAl.jpg"],
			thumbnail: "https://i.imgur.com/w4HPbrr.jpg",
			title: "Hooters Lucina (Vallurite)",
			artist: "Vallurite",
			artist_url: "https://twitter.com/Vallurite",
			art_url: "https://twitter.com/Vallurite/status/1394692198151688192",
			desc: "I love how this one turned out. Her smile is so nice, and I really like Vallurite's style.",
			date_str: "May 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/c6WlxG6.png", "https://i.imgur.com/vMKoJ4z.png"],
			thumbnail: "https://i.imgur.com/TOzgr8P.jpg",
			title: "Hooters Lucina (SonicHeroXD)",
			artist: "SonicHeroXD",
			artist_url: "https://twitter.com/SonicHeroXD",
			art_url: "https://twitter.com/SonicHeroXD/status/1399120844639584261",
			desc: "It was wonderfully done by SonicHeroXD! <3 There is also a spicy lingerie variant!",
			date_str: "May 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/AkMNIvr.jpg"],
			thumbnail: "https://i.imgur.com/l90cVfD.jpg",
			title: "Hooters Lucina (m1n0f2e1_)",
			artist: "m1n0f2e1_",
			artist_url: "https://twitter.com/m1n0f2e1_",
			art_url: "https://skeb.jp/@m1n0f2e1_/works/6",
			desc: "This was my first Skeb commission. It turned out very cute! I really love the brightness of the colors.",
			date_str: "June 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/UCipSh3.jpg", "https://i.imgur.com/wLaZUYk.png"],
			thumbnail: "https://i.imgur.com/QWmbES4.jpg",
			title: "Hooters Lucina (PPPMMMRRROOO)",
			artist: "PPPMMMRRROOO",
			artist_url: "https://twitter.com/PPPMMMRRROOO",
			art_url: "https://skeb.jp/@PPPMMMRRROOO/works/1",
			desc: "This one has two versions: one with warmer lighting and one with cooler lighting. I like the sitting pose, which was something new and different at the time.",
			date_str: "June 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/1swR4Cg.jpg"],
			thumbnail: "https://i.imgur.com/rUjzNRE.jpg",
			title: "Hooters Lucina (nekko_donburi)",
			artist: "nekko_donburi",
			artist_url: "https://twitter.com/nekko_donburi",
			art_url: "https://skeb.jp/@nekko_donburi/works/1",
			desc: "Another one with her sitting down but with a view from behind instead. It's really creative how the background resembles beer.",
			date_str: "June 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/mv7v0xR.jpg"],
			thumbnail: "https://i.imgur.com/HwNTLdH.jpg",
			title: "Lucina HYPE!!!! (Vallurite)",
			artist: "Vallurite",
			artist_url: "https://twitter.com/Vallurite",
			art_url: "https://twitter.com/Vallurite/status/1403458247458275345",
			desc: "I love the lines that emphasize this moment of hype. LET'S GOOO!",
			date_str: "June 2021",
			tags: [""],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/lVHF8Bh.jpg"],
			thumbnail: "https://i.imgur.com/ualTckk.jpg",
			title: "Hooters Lucina (Densho_Hiyoko)",
			artist: "Densho_Hiyoko",
			artist_url: "https://twitter.com/Densho_Hiyoko",
			art_url: "https://twitter.com/Densho_Hiyoko/status/1403724784450506752",
			desc: "I commissioned Densho_Hiyoko, who draws cute chibi Lucina doodles on Twitter, to draw a Hooters Lucina. She turned out so cute and pretty!",
			date_str: "June 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/ccyatcl.jpg"],
			thumbnail: "https://i.imgur.com/Mt00W76.jpg",
			title: "Hooters Lucina (wawatiku)",
			artist: "wawatiku",
			artist_url: "https://twitter.com/wawatiku",
			art_url: "https://twitter.com/wawatiku/status/1407901143443800064",
			desc: "This time it was done by wawatiku. It's lovely! I especially love the hair and the background - it's all so pretty.",
			date_str: "June 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/CM2hePj.jpg"],
			thumbnail: "https://i.imgur.com/x0nj0fL.jpg",
			title: "Hooters Lucina (AKN_646)",
			artist: "AKN_646",
			artist_url: "https://twitter.com/AKN_646",
			art_url: "https://twitter.com/akn_646/status/1408456950728118275",
			desc: "This time is by AKN. Very cute and very pretty - I love it!",
			date_str: "June 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/kTenxhH.jpg"],
			thumbnail: "https://i.imgur.com/qyukxm0.jpg",
			title: "Hooters Lucina (Ihsnet)",
			artist: "Ihsnet",
			artist_url: "https://twitter.com/Ihsnet",
			art_url: "https://twitter.com/Ihsnet/status/1409003004351635457",
			desc: "This time it's done by Ihsnet! I especially like the long legs and how the boots resemble those from her regular outfit.",
			date_str: "June 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/iQA108g.png"],
			thumbnail: "https://i.imgur.com/JDwWXz8.jpg",
			title: "Hooters Lucina (SMGold)",
			artist: "SMGold",
			artist_url: "https://twitter.com/SMGold_",
			art_url: null,
			desc: "It's wonderful! I love the pose and expression: demure but still warm.",
			date_str: "June 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/jCdkav2.png"],
			thumbnail: "https://i.imgur.com/Fwvi94d.jpg",
			title: "Hooters Lucina (B_PearlWhite)",
			artist: "B_PearlWhite",
			artist_url: "https://twitter.com/B_PearlWhite",
			art_url: "https://twitter.com/B_PearlWhite/status/1410617732656107529",
			desc: "This is the only one with full-leg leggings other than the original Hooters Lucina from a few years ago (there are a few with stockings and boots however). I also like the bubbly background. It's very nice!",
			date_str: "July 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/8WO5lvZ.png"],
			thumbnail: "https://i.imgur.com/PIbWnGJ.jpg",
			title: "Hooters Lucina (frogbians)",
			artist: "frogbians",
			artist_url: "https://twitter.com/frogbiansVEVO",
			art_url: "https://twitter.com/frogbiansVEVO/status/1417535041949691904",
			desc: "I really like the design of the cute footwear and legwear as well as the food!",
			date_str: "July 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/cVwQh9z.jpg"],
			thumbnail: "https://i.imgur.com/cUaFeGL.jpg",
			title: "Hooters Lucina (zaki_btw)",
			artist: "zaki_btw",
			artist_url: "https://twitter.com/zaki_btw",
			art_url: null,
			desc: "The atmosphere of this piece is great, and the lighting and shading help capture it really well.",
			date_str: "July 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/IdkEhPb.png"],
			thumbnail: "https://i.imgur.com/UVAQhqV.jpg",
			title: "Hooters Lucina (harunn2288)",
			artist: "harunn2288",
			artist_url: "https://twitter.com/harunn2288",
			art_url: "https://skeb.jp/@harunn2288/works/76",
			desc: "This is harunn's take on Hooters Lucina, and it turned out really pretty! Her smile is cute, and the lines in the background make this piece seem dynamic and lively!",
			date_str: "July 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/on6FNHP.jpg", "https://i.imgur.com/MqbFNgs.jpg"],
			thumbnail: "https://i.imgur.com/jH9IJ5E.jpg",
			title: "Hooter Lucina (kalruna)",
			artist: "kalruna",
			artist_url: "https://twitter.com/kalruna_art",
			art_url: "https://twitter.com/kalruna_art/status/1430968289182760962",
			desc: "This is kalruna's Hooters Lucina! This has a shirt-on version and a topless version. I really love the warm colors, lighting, and tone. She's enjoying a mug of beer by the bar after a long day of work. It's so very nice and cozy!",
			date_str: "July 2021",
			tags: ["hooters", "nsfw"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/PRhT6Tt.png"],
			thumbnail: "https://i.imgur.com/fZqwoFj.jpg",
			title: "Hooters Lucina (BBK13zK)",
			artist: "BBK13zK",
			artist_url: "https://twitter.com/bbk13z",
			art_url: "https://twitter.com/bbk13z/status/1422017312316481538",
			desc: "BBK's Hooters Lucina! Again, Lucina's smile is so nice. A happy Lucina is a great Lucina! The heels are a nice touch too. Very pretty!",
			date_str: "July 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/vMXEesI.jpg"],
			thumbnail: "https://i.imgur.com/rcMOXEj.jpg",
			title: "Hooters Lucina (Patdarux Dream)",
			artist: "Patdarux Dream",
			artist_url: "https://twitter.com/patdarux",
			art_url: "https://twitter.com/patdarux/status/1419066117432217600",
			desc: "This is Patdarux's Hooters Lucina! I like the cute Feh in the logo on the shirt, and I really like the seaside paradise background!",
			date_str: "July 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/lMFDdBV.png"],
			thumbnail: "https://i.imgur.com/YJ2KXWR.jpg",
			title: "Hooters Lucina (azure_monarch)",
			artist: "azure_monarch",
			artist_url: "https://twitter.com/azure_monarch",
			art_url: "https://twitter.com/azure_monarch/status/1419380538205380608",
			desc: "The Lucina art community's very own azure_monarch has done a Hooters Lucina! I've watched his growth as an artist for a long while now, and I look forward to his future work. I really like Lucina's smile and the beer, and the lighting is impressive! Keep it up!<br/>azure_monarch also came up with Hooters Lucina independently from me back in 2018 in this <a href='https://twitter.com/azure_monarch/status/981019322209337344' target='_blank'>Tweet</a>.",
			date_str: "July 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/tHCuhq4.jpg"],
			thumbnail: "https://i.imgur.com/6uW38Cp.jpg",
			title: "Lifeguard Lucina (GrimmelsDaThird)",
			artist: "GrimmelsDaThird",
			artist_url: "https://twitter.com/GrimmelsDaThird",
			art_url: "https://twitter.com/GrimmelsDaThird/status/1419697741681156098",
			desc: "A nice summertime piece of Lucina in a red lifeguard one-piece swimsuit. We've gotten a lot of different types of swimsuit art for Lucina, but I haven't seen a lifeguard one. A nice refreshing piece for a hot summer's day!",
			date_str: "July 2021",
			tags: [""],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/sTeqn0d.jpg"],
			thumbnail: "https://i.imgur.com/gBLQlwG.jpg",
			title: "Hooters Lucina & Tomboy Outback Lucina (cluseller)",
			artist: "cluseller",
			artist_url: "https://twitter.com/cluseller",
			art_url: "https://skeb.jp/@cluseller/works/60",
			desc: "Hooters Lucina with a Tomboy Outback Lucina by cluseller! This was an idea pitched to me by a friend, and I knew cluseller was the right artist for the job. I love their smiles and the deep blue of the hair (long and short). It turned out so wonderfully, and they're both so pretty. Which invitation would you accept?",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/E38bzcp.png"],
			thumbnail: "https://i.imgur.com/KbMnsNm.jpg",
			title: "Hooters Lucina (joysjsj00)",
			artist: "joysjsj00",
			artist_url: "https://www.instagram.com/joysjsj00/",
			art_url: null,
			desc: "This is a Hooters Lucina by Joy. This turned out really pretty and really cute! The artist was also great and very friendly. Lucina looks a little shy, but the pose shows confidence. And I really like how that's depicted.",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/nngQwJF.png"],
			thumbnail: "https://i.imgur.com/ZbLlw54.jpg",
			title: "Hooters Lucina (deeKei)",
			artist: "deeKei",
			artist_url: "https://twitter.com/_deeKei",
			art_url: "https://twitter.com/_deeKei/status/1425890035966959620",
			desc: "This is deeKei's take on Hooters Lucina! It's super pretty! The visor and the ponytail add the sportiness of a sports bar like Hooters. The friendly smile and wink are also very cute!",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/HqPH9Wr.jpg"],
			thumbnail: "https://i.imgur.com/Nic6DtB.jpg",
			title: "Lucina Paizuri (Devilukez10)",
			artist: "Devilukez10",
			artist_url: "https://twitter.com/Devilukez10",
			art_url: "https://twitter.com/Devilukez10/status/1427917077252165632",
			desc: "Lucina tried her best at a titfuck using her small breasts. She looks satisfied with the result! The follow-up sex scene is available <span class='series-link' index='41'>here</span>.",
			date_str: "August 2021",
			tags: ["nsfw"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/OSYbVI2.png"],
			thumbnail: "https://i.imgur.com/OsoD6Kc.jpg",
			title: "Hooters Lucina (NaijMizuho)",
			artist: "NaijMizuho",
			artist_url: "https://twitter.com/SnippyAsianGuy",
			art_url: "https://twitter.com/SnippyAsianGuy/status/1428413308411994113",
			desc: "This is NaijMizuho's very pretty Hooters Lucina! I'm a big fan of his Lucina artwork. I love Lucina's confident pose and, of course, her smile! It's just so pretty!<br/>This was a commission request in response to this <a href='https://twitter.com/SnippyAsianGuy/status/1423506971706208257' target='_blank'>Tweet</a>.",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/76KwElN.jpg"],
			thumbnail: "https://i.imgur.com/1krLRAI.jpg",
			title: "Hooters Lucina (tsunsune)",
			artist: "tsunsune",
			artist_url: "https://twitter.com/tsunsune",
			art_url: "https://twitter.com/tsunsune/status/1429400204013314052",
			desc: "This is tsunsune's Hooters Lucina! The artwork turned out so pretty: the lighting, colors, and atmosphere are so nice and bright and inviting. It's as if Lucina herself is waiting on you with a cute smile on her face! :D",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/0KRih0U.jpg"],
			thumbnail: "https://i.imgur.com/ALgsgOo.jpg",
			title: "Hooters Lucina (RayDango)",
			artist: "RayDango",
			artist_url: "https://twitter.com/ray_dango",
			art_url: "https://twitter.com/ray_dango/status/1429883492670840834",
			desc: "Hooters Lucina by RayDango! She looks super cute here, and RayDango's style adds to the cuteness really well. Service with a smile... and a bonus wink!",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/Ir796bU.png"],
			thumbnail: "https://i.imgur.com/xeRckC3.jpg",
			title: "Hooters Lucina (graysheartart)",
			artist: "graysheartart",
			artist_url: "https://twitter.com/graysheartart",
			art_url: null,
			desc: "I really like the outfit design for this: the tied-up shirt, the cute visor, and the orange socks. It turned out really cute, and it has a really refreshing quality about it!",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: true
		},
		{
			src: ["https://i.imgur.com/HwvGRJk.png"],
			thumbnail: "https://i.imgur.com/Amhda50.jpg",
			title: "Hooters Lucina (ArcEdo)",
			artist: "ArcEdo",
			artist_url: "https://twitter.com/Arc_Edo11",
			art_url: "https://twitter.com/Arc_Edo11/status/1435686491846553603",
			desc: "ArcEdo's Hooters Lucina is so pretty, and I love how it turned out! Feh the owl on the logo is always a hoot. The colors are all very lovely. Lucina's smile is also so precious. :) Nicely done!",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/ZXMy5az.png"],
			thumbnail: "https://i.imgur.com/oRpXHei.jpg",
			title: "Hooters Lucina (John Caden)",
			artist: "John Caden",
			artist_url: "https://twitter.com/JohnCaden64",
			art_url: "https://twitter.com/JohnCaden64/status/1431299136830197765",
			desc: "This is a Hooters Lucina by John Caden! It's so cute and so pretty! I love John's style, and I've been a fan of his Lucina artwork for a while. This was done amazingly well, and I especially like the expression he chose to draw! Please consider checking out his art on Twitter!",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/Qzzp5Xa.jpg"],
			thumbnail: "https://i.imgur.com/hFeuim5.jpg",
			title: "Hooters Lucina (eva02marina0)",
			artist: "eva02marina0",
			artist_url: "https://twitter.com/eva02marina0",
			art_url: "https://twitter.com/eva02marina0/status/1432698692608405511",
			desc: "This is Mari's Hooters Lucina artwork! I'm stunned by how beautiful this is. Lucina looks so pretty and so cute here! I love the bright and warm colors and, of course, Lucina's smile. It's all so lovely!",
			date_str: "August 2021",
			tags: ["hooters"],
			hidden: true
		},
		{
			src: ["https://i.imgur.com/kbpAZ1W.png"],
			thumbnail: "https://i.imgur.com/PB9ZMhm.jpg",
			title: "Hooters Lucina (OrenjiNoodle)",
			artist: "OrenjiNoodle",
			artist_url: "https://twitter.com/OrenjiNoodle",
			art_url: "https://twitter.com/OrenjiNoodle/status/1436008766353199105",
			desc: "OrenjiNoodle's Hooters Lucina is so cute! I really love how it turned out. The brightness of the colors and the contrast of the blue and orange are so visually nice. Adorable! Amazing work!",
			date_str: "September 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/7ADHqIx.jpg"],
			thumbnail: "https://i.imgur.com/hXiylRj.jpg",
			title: "Hooters Lucina (Seityr)",
			artist: "Seityr",
			artist_url: "https://twitter.com/Seityr_Art",
			art_url: "https://twitter.com/Seityr_Art/status/1436914514016886792",
			desc: "This is Seityr's Hooters Lucina! The colors give this a really nice refreshing feeling, and I love Lucina's smile and confident pose. It's all very pretty and very well done!",
			date_str: "September 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/G9QwHN2.jpg", "https://i.imgur.com/z6Ahcqy.jpg", "https://i.imgur.com/IxzHnO6.jpg", "https://i.imgur.com/D503m1I.jpg", "https://i.imgur.com/03JLEMK.jpg", "https://i.imgur.com/fd99dy8.jpg", "https://i.imgur.com/4YP001d.jpg", "https://i.imgur.com/UuJFJVF.jpg", "https://i.imgur.com/zb1LgAa.jpg", "https://i.imgur.com/qFN1Z8W.jpg", "https://i.imgur.com/hMhmw44.jpg", "https://i.imgur.com/nZ5n1rf.jpg", "https://i.imgur.com/BVDbGiJ.jpg"],
			thumbnail: "https://i.imgur.com/V5qYbiz.jpg",
			title: "Sex with Summer Lucina (mazenda3378)",
			artist: "mazenda3378",
			artist_url: "https://twitter.com/mazenda3378",
			art_url: "https://skeb.jp/@mazenda3378/works/12",
			desc: "Sex with Lucina in her Cipher swimsuit at the beach! This one came with 9 preset variants by the artist. The provided .psd file also had some other options, so I was able to create some custom variants as well.",
			date_str: "September 2021",
			tags: ["nsfw"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/0rpziUl.png"],
			thumbnail: "https://i.imgur.com/MyMvSSp.jpg",
			title: "Dumb_Lucina (eunnieverse)",
			artist: "eunnieverse",
			artist_url: "https://twitter.com/eunnieverse",
			art_url: null,
			desc: "This is the eunnieverse signature \"Dumb\" character art. This one is Dumb_Lucina. Very cute!",
			date_str: "September 2021",
			tags: [""],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/TV24SId.png"],
			thumbnail: "https://i.imgur.com/Vvswb6P.jpg",
			title: "Hooters Lucina (Ozkh)",
			artist: "Ozkh",
			artist_url: "https://twitter.com/Ozkh6",
			art_url: null,
			desc: "Ozkh's Hooters Lucina is super pretty! I really like the slightly peeved and tired expression on her face. It's different from the other commissions, and it grants us a view of her busy work shift. It's an amazing piece of artwork! It was also a great experience working with the artist - they were very quick and provided frequent updates.",
			date_str: "September 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/RGLrXJw.jpg"],
			thumbnail: "https://i.imgur.com/9pVxmJw.jpg",
			title: "Hooters Lucina (Desspie)",
			artist: "Desspie",
			artist_url: "https://twitter.com/Desspie",
			art_url: "https://twitter.com/Desspie/status/1442601726842900482",
			desc: "This is a Hooters Lucina by Rain (@Desspie)! It turned out so pretty and so cute - I really love the smile! Including Feh in the logo is always such a nice and cute touch. It's all very lovely with the brightness and the pop of the colors and lighting <3",
			date_str: "September 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/4vA0bMn.jpg", "https://i.imgur.com/4CI6pZm.jpg"],
			thumbnail: "https://i.imgur.com/0CuoXj5.jpg",
			title: "Spooning Sex with Lucina (Devilukez10)",
			artist: "Devilukez10",
			artist_url: "https://twitter.com/Devilukez10",
			art_url: "https://twitter.com/Devilukez10/status/1443083979905593344",
			desc: "This is a follow-up sex scene to the <span class='series-link' index='27'>this titfuck</span> artwork commission. I requested a variant where the man is wearing a condom and a variant where the man creampies Lucina after using up all the condoms.",
			date_str: "September 2021",
			tags: ["nsfw"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/LoVkNFj.png"],
			thumbnail: "https://i.imgur.com/K27SP5k.jpg",
			title: "Hooters Lucina (Mnejing30)",
			artist: "Mnejing30",
			artist_url: "https://twitter.com/Mnejing30",
			art_url: "https://twitter.com/Mnejing30/status/1444584014711427072",
			desc: "This was a Patreon request to Mnejing30. I've seen their other Hooters drawings of Fire Emblem characters, so I sent one for Lucina. I'm a big fan of their sketches, comics, and humor. This artwork is really nice, simple, and pretty - I love Lucina's smile!<br/>You can check out my other Patreon requests <span class='series-link' index='46'>here</span>.",
			date_str: "October 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/U4VbAkn.png"],
			thumbnail: "https://i.imgur.com/vhxHSfq.jpg",
			title: "Barista Lucina (iktk)",
			artist: "iktk",
			artist_url: "https://twitter.com/ika_tko",
			art_url: "https://twitter.com/ika_tko/status/1445458599690608641",
			desc: "This is iktk's gorgeous Lucina as a coffee shop barista. The artwork gives a nice warm and cozy feeling like you're enjoying a nice cup of hot coffee in the shop on an autumn morning. The latte art and her smile are so lovely too!",
			date_str: "October 2021",
			tags: [""],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/5Ha7ij1.png"],
			thumbnail: "https://i.imgur.com/VqZWZT7.jpg",
			title: "Hooters Lucina (jumpaoki)",
			artist: "jumpaoki",
			artist_url: "https://twitter.com/jumpaoki",
			art_url: null,
			desc: "This is a Hooters Lucina by Kenichiro Aoki, who is one of my favorite animators at JC Staff! I really love the pose and the \"camera angle\" of this piece. I also love the vibrant colors and, of course, Lucina's smile!",
			date_str: "October 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/ZNZoeE8.png", "https://i.imgur.com/9fFX6cU.png", "https://i.imgur.com/zALrQKW.png"],
			thumbnail: "https://i.imgur.com/SyvgDGo.jpg",
			title: "Hooters Lucina Blowjob (keiz_0120)",
			artist: "keiz_0120",
			artist_url: "https://twitter.com/keiz_0120",
			art_url: "https://twitter.com/keiz_0120/status/1445713394875596801",
			desc: "This is keiz's artwork of Hooters Lucina giving a blowjob. The artist has drawn lewd Lucina artwork before, so I sent a request for a Hooters Lucina one. It turned out really well! She looks pretty and cute here! I requested cum facial variants - one with a happy, satisfied expression and one with an annoyed expression.",
			date_str: "October 2021",
			tags: ["hooters", "nsfw"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/TUXJzzV.png", "https://i.imgur.com/HItPorg.png", "https://i.imgur.com/dXxPkRo.png", "https://i.imgur.com/nezvR1x.png", "https://i.imgur.com/bibRc9a.png", "https://i.imgur.com/LraH4m5.jpg"],
			thumbnail: "https://i.imgur.com/KWUNEge.jpg",
			title: "Mnejing30 Patreon Requests",
			artist: "Mnejing30",
			artist_url: "https://twitter.com/Mnejing30",
			art_url: null,
			desc: `Various Mnejing30 Patreon requests by me will be posted here with Twitter source links below:<br/>
			<span class='series-link' index='42'>Hooters Lucina</span><br/>
			<a href='https://twitter.com/Mnejing30/status/1446852778492530692' target='_blank'>Chocolate Milk</a><br/>
			<a href='https://twitter.com/Mnejing30/status/1450803527404568576' target='_blank'>Hooters Fjorm</a> (Gift request for YoshaTime)<br/>
			<a href='https://twitter.com/Mnejing30/status/1455135794151051267' target='_blank'>Lucina fighting a giant spider</a><br/>
			<a href='https://twitter.com/mnejing30/status/1458454513082269703' target='_blank'>F!Morgan stacking tomes</a> (Gift request for Exalted)<br/>
			<a href='https://twitter.com/mnejing30/status/1464794100352229377' target='_blank'>Lucina in ASG Lumen's outfit</a> (Gift request for PhantomT)<br/>`,
			date_str: "October 2021 - Present",
			tags: [""],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/rIxbFQY.jpg"],
			thumbnail: "https://i.imgur.com/iOELR8p.jpg",
			title: "Hooters Lucina (1340Smile)",
			artist: "1340Smile",
			artist_url: "https://twitter.com/1340Smile",
			art_url: "https://twitter.com/1340smile/status/1447940124445057025",
			desc: "This is 1340Smile's Hooters Lucina! It's so very nice, and I really like how dynamic it is. You can really sense the motion and how Lucina is hurrying to deliver. I hope she does a good job!",
			date_str: "October 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/n3trlW6.jpg", "https://i.imgur.com/NQ1eElH.jpg", "https://i.imgur.com/LvKtpOF.jpg"],
			thumbnail: "https://i.imgur.com/w18KILC.jpg",
			title: "Hooters Lucina Masturbating (mon_eree)",
			artist: "mon_eree",
			artist_url: "https://twitter.com/mon_eree",
			art_url: "https://twitter.com/mon_eree/status/1452303875965284355",
			desc: "This is moneree's Hooters Lucina artwork featuring her masturbating. I really like the legs and the seductive look on her face. It's very inviting!",
			date_str: "October 2021",
			tags: ["hooters", "nsfw"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/oBVKLVk.jpg"],
			thumbnail: "https://i.imgur.com/cOO0UA6.jpg",
			title: "Hooters Lucina (Burnt_Green_Tea)",
			artist: "Burnt_Green_Tea",
			artist_url: "https://twitter.com/Burnt_Green_Tea",
			art_url: "https://twitter.com/Burnt_Green_Tea/status/1453765707448029188",
			desc: "A gorgeous Hooters Lucina by Burnt! I really love the liveliness, the colors, the food detail, and the lighting. It's a great vivid piece of art with a cute and pretty smile from Lucina!",
			date_str: "October 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/mbpcFyR.jpg"],
			thumbnail: "https://i.imgur.com/L36oHkt.jpg",
			title: "Lucina Eating Pizza (picnicic)",
			artist: "picnicic",
			artist_url: "https://twitter.com/picnicic",
			art_url: "https://twitter.com/picnicic/status/1454444316269547520",
			desc: "A simple commission by picnicic of Lucina enjoying a slice of pizza. Not sure if pizza exists in Ylisse, but you can make one in FEH's Dining Hall.",
			date_str: "October 2021",
			tags: [""],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/U4DLmFn.jpg"],
			thumbnail: "https://i.imgur.com/17Fo1Xt.jpg",
			title: "Oktoberfest Lucina (kh_kyo_hibiki / mattsun!)",
			artist: "kh_kyo_hibiki / mattsun!",
			artist_url: "https://twitter.com/kh_kyo_hibiki",
			art_url: "https://skeb.jp/@kh_kyo_hibiki/works/6",
			desc: "I got the opportunity to commission kh_kyo_hibiki/mattsun! (FEH artist for Tanya and Bride Tanith) to produce this gorgeous artwork of Lucina at Oktoberfest. I really love Lucina's beautiful dirndl dress, especially the big cute bow on the side. I hope she enjoys her time having fun and eating good food in this festive autumn atmosphere.",
			date_str: "November 2021",
			tags: [""],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/4tmgTul.jpg"],
			thumbnail: "https://i.imgur.com/LR307RQ.jpg",
			title: "\"At the Intersection of Despair and Hope\" ft. Exalt Morgan, Mo-Mo, and Lucina (AcrylicStroke)",
			artist: "AcrylicStroke",
			artist_url: "https://twitter.com/AcrylicStroke",
			art_url: "https://twitter.com/AcrylicStroke/status/1456635598463135755",
			desc: "\"At the Intersection of Despair and Hope\": This is a joint commission I requested with Exalted! The artist AcrylicStroke did a wonderful job creating this artwork. The idea was to request a piece resembling a movie poster of Exalt Morgan and Fallen Morgan (Mo-Mo) facing each other and determined to battle while Lucina watches over and prays that hope may not die. We hope you enjoy the art, and please consider checking out the AcrylicStroke!",
			date_str: "November 2021",
			tags: [""],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/KNwJGH2.jpg", "https://i.imgur.com/zRKiS9a.jpg"],
			thumbnail: "https://i.imgur.com/obP7Q9P.jpg",
			title: "Hooters Lucina (PomeloMelon1)",
			artist: "PomeloMelon1",
			artist_url: "https://twitter.com/PomeloMelon1",
			art_url: "https://twitter.com/PomeloMelon1/status/1456663767190810628",
			desc: "This is PomeloMelon1's Hooters Lucina! I'm a big fan of their art. I love the lighting/shading and Lucina's expression: the confidence and the slight smugness when she looks at you the viewer. I also like how she plays with her hair; it really adds to that aura of confidence. There is a also a variant with the black-colored uniform.",
			date_str: "November 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/YWlmxn3.png"],
			thumbnail: "https://i.imgur.com/ThKnL8L.jpg",
			title: "Hooters Lucina (Paulygon2)",
			artist: "Paulygon2",
			artist_url: "https://twitter.com/Paulygon_2",
			art_url: "https://twitter.com/Paulygon_2/status/1456082126042976257",
			desc: "This is a unique type of commission: a FEH-style chibi of Hooters Lucina by Paulygon2. I think it's absolutely adorable! Paulygon2 did an excellent job on creating the custom outfit, and I especially love the little chibi Feh on the shirt too!",
			date_str: "November 11",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/8HL1XDQ.jpg"],
			thumbnail: "https://i.imgur.com/VWRIXZG.jpg",
			title: "Hooters Lucina (Xith)",
			artist: "Xith",
			artist_url: "https://twitter.com/x_Xith_x",
			art_url: "https://twitter.com/x_Xith_x/status/1457122193272446979",
			desc: "This is Xith's Hooters Lucina! I really like the angles, the perspective, and the contrast of the lighting and shading. The blowing wind also makes the piece feel like it's moving, fluid, and dynamic. And a nice large mug of frothy beer for you!",
			date_str: "November 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/KGlI6JP.jpg"],
			thumbnail: "https://i.imgur.com/npUkYYz.jpg",
			title: "Hooters Lucina (KiritzuguArt)",
			artist: "KiritzuguArt",
			artist_url: "https://twitter.com/KiritzuguArt",
			art_url: "https://twitter.com/KiritzuguArt/status/1458078246193541123",
			desc: "This is Kiritzugu's Hooters Lucina! She looks so pretty! It's amazing artwork! The artist decided on a unique facial expression and outfit design from the rest, and I really like both! It's so wonderfully done and so lovely. It was great working with the artist, and I loved seeing the progress on stream.",
			date_str: "November 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/qtCmZEX.png"],
			thumbnail: "https://i.imgur.com/cyofeqL.jpg",
			title: "Hooters Lucina (tenchan_man)",
			artist: "tenchan_man",
			artist_url: "https://twitter.com/tenchan_man",
			art_url: "https://twitter.com/tenchan_man/status/1461541232375595011",
			desc: "This is tenchan_man's Hooters Lucina! She looks so pretty! I love the colors, lighting, and highlights. I also love Lucina's confident smile and pose!",
			date_str: "November 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/xnWMj9H.jpg"],
			thumbnail: "https://i.imgur.com/mXulc2f.jpg",
			title: "Survey Corps Lucina (Saiykik)",
			artist: "Saiykik",
			artist_url: "https://twitter.com/Saiykik",
			art_url: "https://twitter.com/Saiykik/status/1461096513602527240",
			desc: "Dedicate your heart! This is a commission of Lucina as a Survey Corps member flying around with the ODMG/3DMG and dual wielding two Falchions (she borrowed Chrom's). The artwork was wonderfully done by Saiykik! It's a great action pose as if she's about cut down Grima's nape. Lucina's Japanese VA, Yu Kobayashi, also happens to voice Sasha, my favorite character from Attack on Titan.",
			date_str: "November 2021",
			tags: [""],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/82soMRT.jpg"],
			thumbnail: "https://i.imgur.com/uWIJf1z.jpg",
			title: "Hooters Lucina (Omiza_Zu)",
			artist: "Omiza_Zu",
			artist_url: "https://twitter.com/Omiza_Zu",
			art_url: "https://twitter.com/omiza_zu/status/1466131711272570889",
			desc: "This is Omiza SOmi's Hooters Lucina (Omiza_Zu on Twitter)! She's so pretty! I love how her hair was drawn, and I also love Lucina's smile and confident pose! It's amazing work!",
			date_str: "November 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: ["https://i.imgur.com/XKHbmR2.jpg"],
			thumbnail: "https://i.imgur.com/K959Pwz.jpg",
			title: "Hooters Lucina (fumaimpact)",
			artist: "fumaimpact",
			artist_url: "https://twitter.com/fumaimpact",
			art_url: "https://twitter.com/fumaimpact/status/1465529600029560836",
			desc: "This is a Hooters Lucina by FumaFu (fumaimpact on Twitter)! It's amazing! She looks so cute and happy, and I love the energy and the colors. The sparkles also give this piece life, and the moving foam of the beer makes it feel dynamic. It turned out so nicely!",
			date_str: "November 2021",
			tags: ["hooters"],
			hidden: false
		},
		{
			src: [""],
			thumbnail: "",
			title: "",
			artist: "",
			artist_url: "",
			art_url: "",
			desc: "",
			date_str: "",
			tags: [""],
			hidden: true
		}
	]
};